root = "."
tmp_dir = "tmp"
[build]
cmd = "make build"
bin = "myapp"
full_bin = "APP_ENV=dev APP_USER=air ./myapp"
include_ext = ["go", "templ", "sql"]
exclude_dir = ["tmp", "vendor"]
[run]
skip_init = true