services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=videla
      - POSTGRES_PASSWORD=XYZ
      - POSTGRES_DB=tarjetasdb
    ports:
      - 5432:5432
    volumes:
      - ./db/Schema/schema.sql:/docker-entrypoint-initdb.d/init.sql